### ISSUE TITLE
How to get SDK token?

### ISSUE THREAD

**Issue by junaidlodhi22** [ItachiUchiha0/payfort_plugin#1]
Hi thank you for the plugin?
Can you guide me how to get SDK token. Is there any option in this package to get that? or i have to do that natively?

**Comment by junaidlodhi22** [comment]
I am right now using Payfort REST API in flutter using web view to get token_name parameter but unable to make a purchase! Getting signature mismatch error.
Any help would be great

**Comment by ItachiUchiha0** [comment]
Hello @junaidlodhi22, you are welcome.
In this plugin you use #getID method to get device ID from payfort then you should send it to your backend.
from backend you will use this ID to generate an SDK token using payfort api  and use it for the payment request.

**Comment by ItachiUchiha0** [comment]
Hello @junaidlodhi22 ,
I hope you are done.
Thank you.
